config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] { put :sort, on: :collection }
  resources :topics, only: [:index, :show]
  resources :resume_items
  resources :blogs, path: 'blog'

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'resume_item/:id', to: 'resume_items#show', as: 'resume_item_show'

  get 'resume', to: 'pages#resume', path: 'experience'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'about-me', to: 'pages#about'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  default_scope {order(created_at: :desc)}

  enum status: { draft: 0, published: 1 }
  
  validates_presence_of :title, :body, :topic_id, :description

  belongs_to :topic
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :topics_for_sidebar, only: [:index, :show, :edit, :new]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.page(params[:page]).per(5)
    else
      @blogs = Blog.page(params[:page]).per(5).published
    end
    @page_title = "Bradley Campbell | Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      # @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: 'Not authorized to access this page.'
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, error: 'Your blog was submitted.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post was removed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
        
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status, :description)
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, 
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :lax_html_blocks => true,
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe

  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <p class="blog-post-meta">
    <%= link_to blog.status.split.map(&:capitalize).join(' '), toggle_status_blog_path(blog) %> /
    <%= link_to 'Edit', edit_blog_path(blog), class: "animsition-link" %> /
    <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>   
  </p>
<% end %>

 

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <h3 class="blog-post-title"><%= link_to blog.title.split.map(&:capitalize).join(' '), blog, class: "animsition-link" %></h3>
    <p class="blog-post-meta">Topic: <%= blog.topic.title.split.map(&:capitalize).join(' ') %></p> 
    <p class="blog-post-meta">
    <%= blog.description %>
    </p>
    <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>

    <hr>
</div>           

app/views/blogs/_breadcrumb.html.erb
<nav class="breadcrumb">
  <%= link_to "Home", root_path, class: 'breadcrumb-item animsition-link' %>
  <%= link_to @blog.topic.title, "/topics/#{@blog.topic.title}", class: 'breadcrumb-item animsition-link' %>
  <span class="breadcrumb-item active"><%= @blog.title %></span>
  
  <% if logged_in?(:site_admin)%>
  <span class="pull-right">       
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog), class: "animsition-link" %>
    <%= link_to fa_icon('trash'), @blog, method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %>   
  </span>
  <% end %>

</nav>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
   <% blog.errors.full_messages.each do |error| %>
   <%= alert_generator error %>
  <% end %>
<% end %>

<fieldset class="form-group <%=action_name%>-form-group"> 
    <%= f.label :topic_id %><br>
    <%= f.label :topic_id, "Development", :value => "1", class: "blog-radio" %>
    <div class="form-check <%=action_name%>-form-check">
      <%= f.radio_button :topic_id, "1", class: "form-check-input" %> 
    </div>
    <%= f.label :topic_id, "Debugging", :value => "2", class: "blog-radio" %>
    <div class="form-check <%=action_name%>-form-check">
      <%= f.radio_button :topic_id, "2", class: "form-check-input" %>  
    </div>      
    <%= f.label :topic_id, "Best Practices", :value => "3", class: "blog-radio" %>
    <div class="form-check <%=action_name%>-form-check">
      <%= f.radio_button :topic_id, "3", class: "form-check-input" %> 
    </div>    
    <%= f.label :topic_id, "General Thoughts", :value => "4", class: "blog-radio" %>
    <div class="form-check <%=action_name%>-form-check">
      <%= f.radio_button :topic_id, "4", class: "form-check-input" %>  
    </div>          
    <%= f.label :topic_id, "Live to Ride", :value => "5", class: "blog-radio" %>
    <div class="form-check <%=action_name%>-form-check">
      <%= f.radio_button :topic_id, "5", class: "form-check-input" %>  
    </div>      
</fieldset>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', rows: 12 %>
</div>

<fieldset class="form-group <%=action_name%>-form-group"> 
  <%= f.label :status %><br>
  <%= f.label :status, "Draft", :value => "draft", class: "blog-radio" %>
  <div class="form-check <%=action_name%>-form-check">
    <%= f.radio_button :status, "draft", class: "form-check-input" %> 
  </div> 
  <%= f.label :status, "Published", :value => "published", class: "blog-radio" %>
  <div class="form-check <%=action_name%>-form-check">
    <%= f.radio_button :status, "published", class: "form-check-input" %> 
  </div>
</fieldset>

<div class="form-group">
  <%= f.submit 'Submit Blog Post', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>
    

</div><!-- end /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2> <%= @blog.title.split.map(&:capitalize).join(' ') %></h2>

  <h5> <%= @blog.description %> </h5>

  <%= render partial: "blogs/breadcrumb", locals: { blog: @blog } %>

  <hr>
  <p>
    <%= markdown @blog.body %>
  </p>
</div>