config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] { put :sort, on: :collection }
  resources :topics, only: [:index, :show]
  resources :resume_items
  resources :blogs, path: 'blog'

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'resume_item/:id', to: 'resume_items#show', as: 'resume_item_show'

  get 'resume', to: 'pages#resume', path: 'experience'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'about-me', to: 'pages#about'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  #New model technology, associated with Portfolio, with the has_many/belongs_to
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }


  #The following method ensures that certain data is present when creating a new database entry for respective model
  validates_presence_of :title, :body


  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  # **SCOPE**
  #Defining scope for a model can be done in two ways, the first is using the self method referring to the instance of the class, as in the below two examples:
  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  #**MORE SCOPE***
  #Scope can also be defined as in the two lines below, and this is generally the preferred method for doing so.  
  #The reason this is done here as opposed to in the controller is because it makes for cleaner code, and the controller is really where simple things should be done

  #In the below two lines of code, you are allowing the controller to specifically call out for data assigned to the scope.  
  #You attach a database query to a label, and using that label in the controller will pull only that data... 

  #See portfolio_controller
  scope :ruby, -> {where(subtitle: 'Ruby on Rails')}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, 
                                            :update, 
                                            :show, 
                                            :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end 
  
  def sort
    params[:order].each do |key, value|    
      Portfolio.friendly.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def new
    @portfolio_item = Portfolio.new
  end


  def create
      @portfolio_item = Portfolio.new(portfolio_params)
  
      respond_to do |format|
        if @portfolio_item.save
          format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live!' }
        else
          format.html { render :new }
          end
      end
    end

  def edit
    
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
     
  end

  def destroy
    # Perform lookup
    @portfolio_item = Portfolio.find(params[:id])
    # Destroy/delete the record
    @portfolio_item.destroy
    # Redirect after record is destroyed/deleted
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Your portfolio item was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle,
                                      :link, 
                                      :body, 
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]

                                      )
  end       

end

  def set_portfolio_item
    @portfolio_item = Portfolio.friendly.find(params[:id])
  end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
    "https://placehold.it/#{height}x#{width}"    
  end


  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
    <% if @portfolio_item.errors.any? %>
      <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <%end%>

   <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', rows: 12 %>
  </div>

  <div class="form-group">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: 'form-control', rows: 12 %>
  </div>  

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control', rows: 12 %>
  </div>

  <div class="form-group">
    <label class="btn btn-primary">
      Upload a main image file <%= f.file_field :main_image, style: 'display:none' %>
    </label>

  </div>

  <div class="form-group">
    <label class="btn btn-primary">
      Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none' %>
    </label>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 12 %>
  </div>
    <hr>
  <h3>Technolgies Used:</h3>

  <div>
    <%= f.fields_for :technologies do |technology_form| %>
      <%= render 'technology_fields', f: technology_form %>      
    <% end %>
    <div>
      <%= link_to_add_association 'Add Technolgy', f, :technologies %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit Portfolio Item', class: 'btn btn-outline-secondary'%>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card col-lg-4 col-md-6 col-sm-12" data-id=" <%= portfolio_item.id %> ">
  <div class="portfolio-index-img">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>
  </div>
  <p class="card-text">
    <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item), class: "animsition-link" %>
    <%= portfolio_item.subtitle %>
  </p> 
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'delete', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="col-sm-6 offset-sm-3 portfolio-container">
<h1>Edit this Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted portfolio-background">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <!-- render the partial with a custom name (manual collection vs standard collection), instead of 'portfolio' we had 
      'portfolio_item' so we have to tell rails this using the following syntax: -->
      <%= render partial: 'portfolio_item', collection: @portfolio_items %> 

    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="col-sm-6 offset-sm-3 portfolio-container">

<h1>Create a New Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

</div>

app/views/portfolios/scope.html.erb
<h1>Here is your custom view for your SCOPE</h1>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <div class="portfolio-show-img">
        <%= image_tag portfolio_img(@portfolio_item.main_image, 'main') %>
      </div>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <em> <%= @portfolio_item.subtitle %> </em>

      <p> <%= @portfolio_item.body %> </p>

      <p> <%=  link_to 'Click here to see the project', @portfolio_item.link, class: "animsition-link" if @portfolio_item.link %> </p>

      <h3>Techonologies Used</h3>

      <% @portfolio_item.technologies.each do |t| %>

      <p> <%= t.name %> </p>

      <% end %>
      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to 'edit item', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning animsition-link' %>
      </div>
      <%end%>
    </div>
  </div>
</div>