config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] { put :sort, on: :collection }
  resources :topics, only: [:index, :show]
  resources :resume_items
  resources :blogs, path: 'blog'

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'resume_item/:id', to: 'resume_items#show', as: 'resume_item_show'

  get 'resume', to: 'pages#resume', path: 'experience'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'about-me', to: 'pages#about'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot <%= action_name %>_mastfoot ">
  <div class="inner">
     <p><%= copyright_helper %><p>
  </div>
</div>

app/views/shared/_background.html.erb
<div class="background <%= action_name %>"></div>
<% page = action_name %>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= copyright_helper %> </p>
  <p>
  <a href="#">Back to top</a>&nbsp/&nbsp<%=link_to "Back to Blogs", blogs_path, class: "animsition-link" %>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner" role="listbox">
<div class="carousel-item active">
  <img class="first-slide" src="/assets/macpro-iphone-bw.jpg" alt="First slide">
  <div class="container">
    <div class="carousel-caption d-md-block text-left">
      <h2>Personal Development Blog and Notes</h2>
      <p>Implementation guides and personal notes</p>
    </div>
  </div>
</div>  
<div class="carousel-item">
  <img class="second-slide" src="/assets/black-white-mac-paper.jpg" alt="Second slide">
  <div class="container">
    <div class="carousel-caption d-md-block">
      <h2>Over Seven Years in the Industry</h2>
      <p>I started as an intern for a non-profit in Tucson and earned the position of lead dev. Now I'm a certified engineer with years of experience in all facets of the SDLC.</p>
      <%= link_to "Check out my resume", resume_path, class: "animsition-link btn btn-outline-secondary" %>
    </div>
  </div>
</div>
<div class="carousel-item">
  <img class="third-slide" src="/assets/macbook-black-iphone.jpg" alt="Third slide">
  <div class="container">
    <div class="carousel-caption d-md-block text-right">
      <h2>Arizona Born Software Engineer</h2>
      <p>Sun, coffee, development, application, engineering, and project management; The good life.</p>
       <%= link_to "Read more about me", about_me_path, class: "animsition-link btn btn-outline-secondary" %>
    </div>
  </div>
</div>
</div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">

  <%=  source_helper(" sidebar-module alert alert-info") %>

  <div class="sidebar-module sidebar-module-inset"> 
    <p><%= link_to "Write Blog", new_blog_path, class: "animsition-link"  if logged_in?(:site_admin) %></p>
    <p><%= link_to "New Resume Item", new_resume_item_path, class: "animsition-link"  if logged_in?(:site_admin) %></p>
    <h4>About</h4>
    <p>When I have time I write out simple tutorials and guides for reference. They're really for my own entertainment, but feel free to browse around!</p>
  </div>          

  <div class="sidebar-module sidebar-module-inset">
    <h4>Blogs by Topic</h4>
    <ul>
    <% @topics.collect do |topic| %>
    <li><%= link_to "#{topic.title}", topic, class: "animsition-link" %></li> 
    <% end unless this_url?('resume') %>
    </ul>
  </div>
      
  <div class="sidebar-module">
    <h4>Social Media</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/lihtaes"><%= fa_icon "github" %></a></i></li>
      <li><a href="https://twitter.com/"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.instagram.com/"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://www.facebook.com/"><%= fa_icon "facebook" %></i></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
    <div class="<%= location %>">
    
      <div><%= link_to "home", root_path %></div>
      <div><%= link_to 'about', about_me_path %></div>
      <div><%= link_to 'blog', blogs_path %></div>
      <div><%= link_to 'portfolio', portfolios_path %></div>
      <div><%= link_to 'contact', contact_path %></div>

    </div>

app/views/shared/_notice_alert.html.erb
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

app/views/shared/_portfolio_footer.html.erb
    <footer class="text-muted">
      <div class="container">
        <p class="float-left"> <%= copyright_helper %> </p>
        <p class="float-right">
          <%= link_to "Back to Portfolio", portfolios_path, class: "animsition-link" %>
        </p>
      </div>
    </footer>

app/views/shared/_portfolio_masthead.html.erb
    <!-- start masthead -->
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Previous Projects</h1>
        <p class="lead">Below are some of the sites I've either worked on and maintained, or developed myself in the past.</p>
        <p>
                  <%= link_to 'Learn more about me', about_me_path, class: "animsition-link btn btn-outline-secondary" %>
                  <%= link_to 'Check out my blog!', blogs_path, class: "animsition-link btn btn-outline-secondary" %>
          
          </p>
      </div>
    </section>
    <!-- end masthead -->

app/views/shared/_shared_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse pageNav">
<div class="container">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav mr-auto" >
  <%=  link_to "Bradley Campbell", root_path, class: "animsition-link navbar-brand"  %>
  </div>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav">
      <%= nav_helper 'animsition-link nav-item nav-link', 'li'%>
      <%= login_helper 'animsition-link nav-item nav-link' %>
    </ul>
  </div>
  </div>
</nav>