config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] { put :sort, on: :collection }
  resources :topics, only: [:index, :show]
  resources :resume_items
  resources :blogs, path: 'blog'

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'resume_item/:id', to: 'resume_items#show', as: 'resume_item_show'

  get 'resume', to: 'pages#resume', path: 'experience'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'about-me', to: 'pages#about'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/resume_item.rb
class ResumeItem < ApplicationRecord
  has_many :jobs, dependent: :destroy
  accepts_nested_attributes_for :jobs, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['task'].blank? }

  validates_presence_of :title, :time_there, :tech_used
  
end

app/controllers/resume_items_controller.rb
class ResumeItemsController < ApplicationController
  before_action :set_resume_item, only: [:edit, :update, :destroy]
  access all: {except: [:index, :destroy, :new, :create, :update, :edit, :show]}, site_admin: :all
  layout "blog"

  def index
    @resume_items = ResumeItem.all
    
  end

  def new
    @resume_item = ResumeItem.new 
  end

  def edit
  end

  def show
  end

  def create
    @resume_item = ResumeItem.new(resume_item_params)

    respond_to do |format|
      if @resume_item.save
        format.html { redirect_to resume_path, notice: 'Your resume item was submitted.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume_item.update(resume_item_params)
        format.html { redirect_to resume_path, notice: 'Resume item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @resume_item.destroy
    respond_to do |format|
      format.html { redirect_to resume_path, notice: 'Resume item was removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume_item
      @resume_item = ResumeItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_item_params
      params.require(:resume_item).permit(:title, :time_there, :tech_used, jobs_attributes: [:id, :task, :_destroy])
    end
end

app/helpers/resume_items_helper.rb
module ResumeItemsHelper
end

app/views/resume_items/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <p class="blog-post-meta">
    <%= link_to 'Edit', edit_resume_item_path(resume_item), class: "animsition-link" %> /
    <%= link_to 'Destroy', resume_item, method: :delete, data: { confirm: 'Are you sure?' } %>   
  </p>
<% end %>

 

app/views/resume_items/_form.html.erb
<%= form_for(resume_item) do |f| %>
  <% if resume_item.errors.any? %>
   <% resume_item.errors.full_messages.each do |error| %>
   <%= alert_generator error %>
  <% end %>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :time_there %>
  <%= f.text_field :time_there, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :tech_used %>
  <%= f.text_field :tech_used, class: 'form-control' %>
</div>
<h3>Jobs for resume item:</h3>
<div>
    <%= f.fields_for :jobs do |job_form| %>
      <%= render 'job_fields', f: job_form %>      
    <% end %>
    <div>
      <%= link_to_add_association 'Add Job', f, :jobs %>
    </div>
</div>

<div class="form-group">
  <%= f.submit 'Submit Resume Item', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/resume_items/_job_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :task %>
  <%= f.text_field :task, class: 'form-control' %>
  <%= link_to_remove_association 'delete', f %>
</div>

app/views/resume_items/_resume_item.html.erb
<div class="blog-post">
    <h3 class="blog-post-title"><%= link_to resume_item.title.split.map(&:capitalize).join(' '), edit_resume_item_path(resume_item), class: "animsition-link" %></h3> 
    <%= render partial: 'resume_items/admin_actions', locals: { resume_item: resume_item } %>
    <hr>
</div>           

app/views/resume_items/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Edit Resume Item</h1>

  <%= render 'form', resume_item: @resume_item %>
 
</div>

app/views/resume_items/index.html.erb
<div class="col-sm-8 blog-main">

  <%= render @resume_items %>

</div><!-- end /.blog-main -->

app/views/resume_items/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Resume Item</h1>

  <%= render 'form', resume_item: @resume_item %>
 
</div>